# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: ruff
        name: Check and fix with Ruff
        entry: poetry run ruff check --fix
        language: system
        types: [ python ]

      - id: pylint
        name: Lint with PyLint
        entry: poetry run pylint
        language: system
        types: [ python ]
        args:
          - "app/*"
          - "tests/*"
        require_serial: true

      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [ python ]
        pass_filenames: false
        args:
          - "app"
          - "tests"
