[tool.poetry]
name = "tg-schedule-bot"
version = "0.1.0"
description = ""
authors = ["Mikhail Vlasenko <ya@smkthat.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
